# Spring-boot/cloud application configuration.
#
# Here you can override the spring configuration provided by the Gateway
# by default.
#
# See here for the default provided configuration:
# https://github.com/georchestra/georchestra-gateway/blob/main/gateway/src/main/resources/application.yml

server:
  forward-headers-strategy: FRAMEWORK
  reactive:
    session:
      timeout: 1440m # 24h

spring:
  cloud:
    gateway:
      filter:
        secure-headers:
          referrer-policy: strict-origin
